### ISSUE TITLE
Is it possible to implement a fallback locale?

### ISSUE THREAD

**Issue by mckabi** [jarda-svoboda/sveltekit-i18n#19]
I tried the following code, but failed.

```js
export const config = {
  loaders: [
    { locale: 'en', key: '', 
      loader: () => ({ 'titles.trip': 'Trips', 'titles.events': 'Reports', 'titles.events': 'Events' })
    },
    { locale: 'zh-Hans', key: '', 
      loader: () => ({ 'titles.trip': '旅行' })
    },
  ]
};
export const { t, l, locale, locales, loading, loadTranslations } = new i18n(config);

await loadTranslations('zh-Hans', '/');

const fallbackLocale = 'en';

const tr = (key, ...args) => {
  const message = $t(key, ...args);
  return (key === message) ? $l(fallbackLocale, key, ...args) : message;
}

// output
// $locale = zh-Hans
// $locales = (3) ['en', 'zh-Hans', 'zh-hans']

tr('titles.trip') → '旅行' → OK
tr('titles.report') → 'titles.report' → Not 'Reports'
tr('titles.events') → 'titles.events' → Not 'Events'
```

Why $locales is not `['en', 'zh-Hans']`?
`$l(locale, key)` is working?

Thank you.

**Comment by jarda-svoboda** [comment]
Hi @mckabi, thanks for your comment! Unfortunately, `fallbackLocale` is currently not implemented. `$l` doesn’t load anything (it just returns already loaded translations for given locale – docs updated – thanks), so in your example, you would have to include load for your fallback translations:

```javascript

export const { t, l, locale, locales, loading, loadTranslations, getTranslationProps, addTranslations } = new i18n(config);

await loadTranslations('zh-Hans', '/');

const fallbackLocale = 'en';

const tr = async (key, ...args) => {
  const message = $t(key, ...args);

  if (key === message) {
    const props = await getTranslationProps(fallbackLocale);
    if (props.length) addTranslations(...props);

    return $l(fallbackLocale, key, ...args);
  }
  return message;
}
```

However, i think, that `fallbackLocale` is useful, so i'll implement config property for it in version 1.4.0 😉

$locales should include `['en', 'zh-hans']` in your case (i would like to keep it case insensitive, so comparison should be in lower-case format), but it seems you've found a bug.. i'll fix this in the next version as well.)

**Comment by mckabi** [comment]
Awesome.

Nice hint and Thanks for your brilliant job. :smile:

**Comment by ralyodio** [comment]
using `navigator.language` does not work. I get an error saying `navigator is undefined`

**Comment by mckabi** [comment]
@ralyodio `navigator` requires browser. call later.

**Comment by jarda-svoboda** [comment]
@ralyodio When you have SSR in SvelteKit turned on, it renders on server first, where is no `navigator`… 
Alternatively, you could use different approach for example SvelteKit's `hooks` and request headers..
