### ISSUE TITLE
Translation when importing components after translations

### ISSUE THREAD

**Issue by Slepzs** [jarda-svoboda/sveltekit-i18n#26]
Vite compiler is puking when I try to add translations before the button component.  

```
<script>
  import { t } from "$lib/translations";
  import Button from "../components/base/Button.svelte";

</script>

<Button>{$t("common.menu.booking")}</Button>
```

This is my lang file setup 

```
import i18n from "sveltekit-i18n";
import lang from "./lang.json";
export const config = {
  translations: {
    en: { lang },
    da: { lang },
    se: { lang },
  },
  loaders: [
    {
      locale: "en",
      key: "common",
      loader: async () => (await import("./en/common.json")).default,
    },
    {
      locale: "da",
      key: "common",
      loader: async () => (await import("./da/common.json")).default,
    },
    {
      locale: "se",
      key: "common",
      loader: async () => (await import("./se/common.json")).default,
    },
  ],
};

export const { t, locale, locales, loading, loadTranslations } = new i18n(
  config
);

loading.subscribe(
  ($loading) => $loading && console.log("Loading translations...")
);

```

Vite error:

 Internal server error: Cannot find module 'C:\Projects\projectname\package.json' imported from 'C:\Projects\projectname\node_modules\vite\dist\node\chunks\dep-f5552faa.js'

I'm using sveltekit with svelte add and Tailwind

**Comment by jarda-svoboda** [comment]
On a first look, It seems to me like some error in Vite compiler, but I’ll try to replicate (or if you have some repro? - would be useful) and let you know..)

**Comment by Slepzs** [comment]
I created this repo, so you can test it. The primary problem happens in the payment route.

https://github.com/Slepzs/Translations_error

**Comment by jarda-svoboda** [comment]
Your repro looks fine, only one thing - you are missing lang init:

```svelte
<script context="module">
  import { locale,  loadTranslations } from '$lib/translations';
  
  export const load = async ({ url }) => {
    const { pathname } = url;

    const lang = locale.get() || 'en';

    await loadTranslations(lang, pathname);

    return {};
  }
</script>
```

I wasn't able to replicate your error, though.. Have you tried to update your deps to latest versions?

**Comment by Alexnortung** [comment]
Try now at this fork https://github.com/Alexnortung/Translations_error

to reproduce the error run `npm run dev`, then go to `localhost:3000/booking` and there will be errors.
However if you start `npm run dev` then go to `localhsot:3000/` and then to `localhost:3000/booking` there won't be any errors.

**Comment by jarda-svoboda** [comment]
@Alexnortung thanks for your repro, but still no errors in server nor client console on my side even if i directly go to `/booking` – what OS do you use? I'm trying on macOS – maybe this issue is OS related...🤔

**Comment by jarda-svoboda** [comment]
Ok, this error is caused by imports in `__layout.svelte` from your repro:
```js
  // This throws me the error:
  import { lang } from "$lib/stores/lang";
  import { t, locales, locale, loadTranslations } from "$lib/translations";

  // This seems to be ok:
  import { t, locales, locale, loadTranslations } from "$lib/translations";
  import { lang } from "$lib/stores/lang";
```

But it does not seem to be related directly to this library – it seems to be more like SvelteKit / Vite / preprocessor related bug...
